package com.truvaile;

import java.io.IOException;  
import java.io.PrintWriter;  
  
import javax.servlet.ServletException;  
import javax.servlet.annotation.WebServlet;  
import javax.servlet.http.HttpServlet;  
import javax.servlet.http.HttpServletRequest;  
import javax.servlet.http.HttpServletResponse;  
@WebServlet("/EditServlet")  
public class EditServlet extends HttpServlet {  
   private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)   
           throws ServletException, IOException {  
        response.setContentType("text/html");  
        PrintWriter out=response.getWriter();  
        String sid=request.getParameter("id");  
       
          
        Emp e=EmpDao.getEmployeeById(sid);  
          
         out.print("<!DOCTYPE html>\r\n"
        		+ "<html lang=\"en\">\r\n"
        		+ "<head>\r\n"
        		+ "<meta charset=\"ISO-8859-1\">\r\n"
        		+ "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
        		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
        		+ "    <title> Add Package | Truvaile</title>\r\n"
        		+ "    <link rel=\"icon\" href=\"/Images/logo01.png\">\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"css/style08.css\">\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"css/style07.css\">\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.1.1/css/all.css\" integrity=\"sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ\" crossorigin=\"anonymous\">\r\n"
        		+ "     <style>\r\n"
        		+ "        .save{\r\n"
        		+ "           margin:1rem 3.5rem ;\r\n"
        		+ "            }\r\n"
        		+ "         tr, td{\r\n"
        		+ "         margin-top: 1rem; \r\n"
        		+ "         }\r\n"
        		+ "    </style>\r\n"
        		+ "     <style>\r\n"
        		+ "        .wrapper{\r\n"
        		+ "  width: 700px; box-shadow: 0px 15px 20px #009879; border: 1px solid black;" 
        		+ "}\r\n"
        		+ "\r\n"
        		+ "    </style>\r\n"
        		+"<style> .wrapper .title{ background: linear-gradient(-135deg,#D1FAE5,white);}</style>"
        		+ "</head>\r\n"
        		+ "<body>\r\n"
        		+ "<header class=\"main\">\r\n"
        		+ "        <div class=\"header-cotainer\">\r\n"
        		+ "           <div class=\"top-container\">\r\n"
        		+ "                <nav class=\"navigation container\">\r\n"
        		+ "                    <div class=\"nav-brand\">Truvaile</div>\r\n"
        		+ "                    <ul class=\"list-non-bullet nav-pills\">\r\n"
        		+ "                        <li class=\"list-item-inline\">\r\n"
        		+ "                            <a class=\"link\" href=\"ViewUsers\">Users List</a>\r\n"
        		+ "                        </li>\r\n"
        		+ "                        <li class=\"list-item-inline\">\r\n"
        		+ "                            <a class=\"link link-active\" href=\"ViewServlet\">Packages</a>\r\n"
        		+ "                        </li>\r\n"
        		+ "                        <li class=\"list-item-inline\">\r\n"
        		+ "                            <a class=\"link\" href=\"ViewBookedPackages\">Booked Packages </a>\r\n"
        		+ "                        </li>\r\n"
        		+ "                        <li class=\"list-item-inline\">\r\n"
        		+ "                            <a class=\"link \" href=\"ViewFeedback\">Feedback</a>\r\n"
        		+ "                        </li>\r\n"
        		+ "                        <li class=\"list-item-inline\">\r\n"
        		+ "                            <a class=\"link\" href=\"AdminLogout\">Logout</a>\r\n"
        		+ "                        </li>\r\n"
        		+ "                    </ul>\r\n"
        		+ "                 </nav>\r\n"
        		+ "            </div>\r\n"
        		+ "         </div>\r\n"
        		+ "       </header>\r\n"
        		+ "\r\n"
        		+ " <a href=\"ViewServlet\" style=\"margin-left:23rem; margin-bottom:4rem;  margin-top:4rem;text-decoration: none; font-size: large; text-transform: capitalize;\">View All Packages</a>  \r\n"
        		+ "\r\n"
        		+ "<section class=\"loginform\">\r\n"
        		+ "    <div class=\"wrapper\">\r\n"
        		+ "        <div class=\"title\" style=\"color:black; border-bottom: 1px solid black\">\r\n"
        		+ "  Update Package</div>\r\n"
        		+ "  <form action=\"SaveServlet\" method=\"POST\">\r\n"
        		+ "      <div class=\"field\">\r\n"
        		+ "         <input type='text' class=\"form\" name='id'  value='"+e.getPackage_ID()+"'/>\r\n"
        		+ "           <label>Package ID</label>\r\n"
        		+ "      </div>\r\n"
        		+ "      <div class=\"field\">\r\n"
        		+ "        <input type=\"text\" class=\"form\"  name=\"name\" value='"+e.getPackage_Name()+"'/>\r\n"
        		+ "           <label>Package Name</label>\r\n"
        		+ "      </div>\r\n"
        		+ "       <div class=\"field\">\r\n"
        		+ "         <input type='text'  class=\"form\"  name='type'value='"+e.getPackage_type()+"'/>\r\n"
        		+ "            <label>Package Type</label>\r\n"
        		+ "      </div>\r\n"
        		+ "     <div class=\"field\">\r\n"
        		+ "         <input type='text'  class=\"form\" name='inclusions' value='"+e.getInclusions()+"'/>\r\n"
        		+ "           <label>Package Inclusions</label>\r\n"
        		+ "          </div>\r\n"
        		+ "    <div class=\"field\">\r\n"
        		+ "          <input type='number'  class=\"form\"  name='cost' value='"+e.getPrice_per_person()+"' />\r\n"
        		+ "            <label>Package Cost</label>\r\n"
        		+ "          </div>\r\n"
        		+ "   \r\n"
        		+ "    <div class=\"field\">\r\n"
        		+ "          <select name=\"duration\">  \r\n"
        		+ "              <option>3D/4N</option>  \r\n"
        		+ "              <option>4D/5N</option>  \r\n"
        		+ "              <option>5D/6N</option>  \r\n"
        		+ "              <option>6D/7N</option>  \r\n"
        		+ "          </select>  \r\n"
        		+ "            <label>Package Duration</label>\r\n"
        		+ "          </div>\r\n"
        		+ "     <br><br>\r\n"
        		+ "    <div class=\"field\">\r\n"
        		+ "            <input type=\"submit\" value=\"Save Package\" style=\"color:black;background: linear-gradient(-135deg,#D1FAE5,white); border: 1px solid black;\">\r\n"
        		+ "          </div>\r\n"
        		+ " \r\n"
        		+ "  </form>\r\n"
        		+ "  </div>\r\n"
        		+ "</section>\r\n"
        		+ "<footer class=\"footer\" style=\"margin-top: 2rem;\">\r\n"
        		+ "    \r\n"
        		+ "    <div class=\"footer-header\">\r\n"
        		+ "        <div class=\"icon\">\r\n"
        		+ "            <a href=\"#\" class=\"link\"><i class=\"fas fa-chevron-up\"></i></a></div>\r\n"
        		+ "        <p>© 2020 Truvaile Trips Pvt Ltd.</p>\r\n"
        		+ "    </div>\r\n"
        		+ "    <ul class=\"social-link list-non-bullet\">\r\n"
        		+ "        <li class=\"list-item-inline\">\r\n"
        		+ "           <i class=\"fab fa-linkedin-in\"></i> \r\n"
        		+ "        </li>\r\n"
        		+ "        <li class=\"list-item-inline\">\r\n"
        		+ "            <i class=\"fab fa-facebook-f\"></i> \r\n"
        		+ "        </li>\r\n"
        		+ "        <li class=\"list-item-inline\">\r\n"
        		+ "          <i class=\"fas fa-play\"></i> \r\n"
        		+ "        </li>\r\n"
        		+ "        <li class=\"list-item-inline\">\r\n"
        		+ "           <i class=\"fab fa-instagram\"></i> \r\n"
        		+ "        </li>\r\n"
        		+ "        <li class=\"list-item-inline\">\r\n"
        		+ "          <i class=\"fab fa-twitter\"></i> \r\n"
        		+ "        </li>\r\n"
        		+ "    </ul>\r\n"
        		+ "</footer></body></html>\r\n"
        		+ "\r\n");
          
        out.close();  
    }  
}  