package com.truvaile;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/UserViewPackages")
public class UserViewPackages extends HttpServlet {
	private static final long serialVersionUID = 1L;
 
   protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	   response.setContentType("text/html");  
       PrintWriter out=response.getWriter();  
       out.println("<!DOCTYPE html>\r\n"
       		+ "<html lang=\"en\">\r\n"
       		+ "<head>\r\n"
       		+ "    <meta charset=\"UTF-8\">\r\n"
       		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
       		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
       		+ "    <title> View Packages | Truvaile</title>\r\n"
       		+ "    <link rel=\"icon\" href=\"/Images/logo01.png\">\r\n"
       		+ "    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n"
       		+ "    <!-- <link rel=\"stylesheet\" href=\"css/style05.css\"> -->\r\n"
       		+ "    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.1.1/css/all.css\" integrity=\"sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ\" crossorigin=\"anonymous\">\r\n"
       		+ "    <style>\r\n"
       		+ "    :root{\r\n"
       		+ "    --primary-color: #FCA5A5;\r\n"
       		+ "    --primary-white: white;\r\n"
       		+ "}\r\n"
       		+ "header{\r\n"
       		+ "    background-image: none;\r\n"
       		+ "    height: 20vh;\r\n"
       		+ "}\r\n"
       		+ ".navigation {\r\n"
       		+ "    background-color: var(--primary-white);\r\n"
       		+ "    /* color: white; */\r\n"
       		+ "    /* padding: 2rem; */\r\n"
       		+ "    border-bottom-left-radius: 1rem;\r\n"
       		+ "    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);\r\n"
       		+ "    border: 1px solid #E7E5E4;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".navigation .link, .nav-brand {\r\n"
       		+ "    color: black;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".dropbtn {\r\n"
       		+ "  color: black;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".dropdown-content {\r\n"
       		+ "  background-color: var(--primary-white);\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "section{\r\n"
       		+ "  padding: 0.5rem 0rem;\r\n"
       		+ " \r\n"
       		+ "  height: 100%;\r\n"
       		+ "  width: 90%;\r\n"
       		+ "  margin: 2rem;\r\n"
       		+ "  \r\n"
       		+ "}\r\n"
       		+ ".package-cards{\r\n"
       		+ "    display: inline-flex;\r\n"
       		+ "}\r\n"
       		+ ".card{\r\n"
       		+ "     width: 225px;\r\n"
       		+ "     height: 180px;\r\n"
       		+ "     display: block;\r\n"
       		+ "     box-shadow: 1px 1px 10px rgb(255, 249, 159);\r\n"
       		+ "     border-radius: 5px; \r\n"
       		+ "     margin: 2%;\r\n"
       		+ "     margin-right: 3rem; margin-bottom: 2rem\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".title{\r\n"
       		+ " \r\n"
       		+ "  text-align: center;\r\n"
       		+ "  padding: 10px;\r\n"
       		+ "  \r\n"
       		+ " }\r\n"
       		+ "\r\n"
       		+ "h1{\r\n"
       		+ "  font-size: 20px;\r\n"
       		+ " }\r\n"
       		+ "\r\n"
       		+ ".des{\r\n"
       		+ "  padding: 3px;\r\n"
       		+ "  text-align: center;\r\n"
       		+ " \r\n"
       		+ "  padding-top: 5px;\r\n"
       		+ "  border-bottom-right-radius: 5px;\r\n"
       		+ "  border-bottom-left-radius: 5px;\r\n"
       		+ "}\r\n"
       		+ ".button{\r\n"
       		+ "  margin-top: 5px;\r\n"
       		+ "  margin-bottom: 10px;\r\n"
       		+ "  background-color: white;\r\n"
       		+ "  color: black;\r\n"
       		+ "  border: 1px solid black;\r\n"
       		+ "  border-radius: 5px;\r\n"
       		+ "  padding:10px;\r\n"
       		+ "}\r\n"
       		+ ".button:hover{\r\n"
       		+ "  background-color: black;\r\n"
       		+ "  color:yellow;\r\n"
       		+ "  transition: .5s;\r\n"
       		+ "  cursor: pointer;\r\n"
       		+ "}\r\n"
       		+ ".linktopackages{\r\n"
       		+ "    margin-left: 0.5rem;\r\n"
       		+ "    margin-top: 2rem;\r\n"
       		+ "    /* text-align: center; */\r\n"
       		+ "}\r\n"
       		+ "</style>\r\n"
       		+ "</head>\r\n"
       		+ "<body>\r\n"
       		+ "    <header class=\"main\">\r\n"
       		+ "        <div class=\"header-cotainer\">\r\n"
       		+ "           <div class=\"top-container\">\r\n"
       		+ "                <nav class=\"navigation container\">\r\n"
       		+ "                    <div class=\"nav-brand\">Truvaile</div>\r\n"
       		+ "                    <ul class=\"list-non-bullet nav-pills\">\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <a class=\"link \" href=\"home.html\">Home</a>\r\n"
       		+ "                        </li>\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <a class=\"link\" href=\"about.html\">About us</a>\r\n"
       		+ "                        </li>\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <a class=\"link\" href=\"working.html\">How it works</a>\r\n"
       		+ "                        </li>\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <a class=\"link\" href=\"survey.html\">The Survey</a>\r\n"
       		+ "                        </li>\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <a class=\"link\" href=\"contact.html\">Contact us</a>\r\n"
       		+ "                        </li>\r\n"
       		+ "                        <li class=\"list-item-inline\">\r\n"
       		+ "                            <div class=\"dropdown\" style=\"background-color: transparent;\">\r\n"
       		+ "                                <button class=\"dropbtn\"> \r\n"
       		+ "                                    <i class=\"far fa-user-circle\"></i>\r\n"
       		+ "                                </button>\r\n"
       		+ "                                <div class=\"dropdown-content\">\r\n"                                 
       	    + "                                   <a href=\"MyAccount\">My Account</a><hr/>"
       		+ "                                  <a href=\"Logout\">logout</a>\r\n"
       		+ "                                </div>\r\n"
       		+ "                              </div>\r\n"
       		+ "                        </li>\r\n"
       		+ "                    </ul>\r\n"
       		+ "                 </nav>\r\n"
       		+ "            </div>\r\n"
       		+ "         </div>\r\n"
       		+ "       </header>\r\n"
       		+ "<section class=\"View-Package\" style=\"width:100%;\">\r\n"
       		+ "    <h2 style=\"margin-bottom:1rem ;\">Get Ready to explore more!</h2>");
       
       List<Emp> list=EmpDao.getAllEmployees();
       
 
       
       for(Emp e:list) {
       out.print("<div class=\"package-cards\"><div class=\"card\" style=\"padding: 4rem 4rem;\"><div class=\"title\" style=\" margin-top:-2rem;\"><h1><i>"+e.getPackage_Name()+"</i></h1><br></div><divclass=\"des\"><p style=\" margin-left:-1rem;\">Includes: "+e.getInclusions()+"<br><br>Travel Type: "+e.getPackage_type()+"</p><p><span style=\"float: left; margin-left: -0.5rem; margin-top: 1rem;\">"+e.getNights()+"</span>"
       		+ "<span style=\"float: right; margin-top: 1rem;\">Rs."+e.getPrice_per_person()+"</span></p><br><br><br>"
       		+ " <form action=\"Booking\" method=\"get\">\r\n"
       		+ "              <input type=\"hidden\" style=\"float:left;\" name=\"package_id\" value="+e.getPackage_ID()+">"
       		+ "              <input type= \"submit\" style=\"float:left;\" value=\"BOOK NOW\" class=\"button\"></form>"
//       		+ "              <a href= \"AddToCart\" style=\"float:right; margin-top: 1rem; color:black; font-size:x-large;\" onclick=\"alert('Your package is added to cart')\"><i class=\"far fa-bookmark\" style=\"color:black\"></i></a>"
            + " <form action=\"AddToCart\" method=\"get\">\r\n"
	        + "              <input type=\"hidden\" style=\"float:right;\" name=\"package_id\" value="+e.getPackage_ID()+">"
	        + "              <button class=\"button\" style=\"float:right; color:black; font-size:x-large; border:none; margin-bottom:1rem;\" \"><i class=\"far fa-bookmark\" style=\"color:black\"></i></button></form>"
       		+ "               </div></div></div>");
       }
       
       out.print("</section><footer class=\"footer\"><div class=\"footer-header\"><div class=\"icon\"><a href=\"#\" class=\"link\"><i class=\"fas fa-chevron-up\"></i></a></div><p>© 2020 Truvaile Trips Pvt Ltd.</p></div>"
       		+ "<ul class=\"social-link list-non-bullet\"><li class=\"list-item-inline\"><a href=\"#\" class=\"link\"><i class=\"fab fa-linkedin-in\"></i></a> </li><li class=\"list-item-inline\"><a href=\"#\" class=\"link\"><i class=\"fab fa-facebook-f\"></i></a> </li>"
       		+ "<li class=\"list-item-inline\"><a href=\"#\" class=\"link\"><i class=\"fas fa-play\"></i></a> </li><li class=\"list-item-inline\"><a href=\"#\" class=\"link\"><i class=\"fab fa-instagram\"></i></a> </li><li class=\"list-item-inline\"><a href=\"#\" class=\"link\"><i class=\"fab fa-twitter\"></i></a> "
       		+ "</li></ul></footer></body></html>");
	}

}
